# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

#!/bin/bash

# Run Eval on SSH-Agent and Add Key(s)

if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  echo "Adding Keys..."
  ssh-add
fi

NODE_ENV=development

PROMPT_COMMAND="history -a"

cd /c/Projects
